/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import Entity.User;
import com.formdev.flatlaf.FlatLightLaf;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import dao.UserDAO;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Renderer;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import static org.apache.poi.hssf.usermodel.HeaderFooter.file;
import utils.Check;

/**
 *
 * @author Admin
 */
import static utils.Check.user;
import utils.Encrypt;
import utils.ThongBao;

public class DangNhap extends javax.swing.JDialog {
File file;
    /**
     * Creates new form DangNhap
     */
    public DangNhap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JdlDangNhap = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblQuenMatKhau = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtEmailDangNhap = new javax.swing.JTextField();
        btnDangNhap = new javax.swing.JButton();
        txtPassDangNhap = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        txtQR = new javax.swing.JTextField();
        btnQR = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JdlDangNhap.setBackground(new java.awt.Color(255, 255, 255));
        JdlDangNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("ĐĂNG NHẬP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 26, -1, -1));

        jLabel2.setText("Đăng nhập bằng địa chỉ email của bạn");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 96, 224, -1));

        lblQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuenMatKhau.setForeground(new java.awt.Color(25, 135, 84));
        lblQuenMatKhau.setText("Quên Mật Khẩu?");
        lblQuenMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMatKhauMouseClicked(evt);
            }
        });
        jPanel1.add(lblQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("MÃ QR");
        jLabel10.setAutoscrolls(true);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 90, 30));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("MẬT KHẨU");
        jLabel12.setAutoscrolls(true);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 90, 30));
        jPanel1.add(txtEmailDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 410, 40));

        btnDangNhap.setBackground(new java.awt.Color(25, 135, 84));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("ĐĂNG NHẬP");
        btnDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangNhapMouseClicked(evt);
            }
        });
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 176, 50));
        jPanel1.add(txtPassDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 410, 40));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("EMAIL");
        jLabel11.setAutoscrolls(true);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 90, 30));
        jPanel1.add(txtQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 320, 40));

        btnQR.setText("CHỌN");
        btnQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQRActionPerformed(evt);
            }
        });
        jPanel1.add(btnQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, 40));

        JdlDangNhap.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 68, 630, 510));

        jLabel6.setText("Trang Chủ/");
        JdlDangNhap.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 17, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 204, 51));
        jLabel7.setText("Đăng Nhập");
        JdlDangNhap.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 17, -1, -1));

        getContentPane().add(JdlDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents
      public void checkDangnhap() throws SQLException, IOException, FileNotFoundException, NotFoundException {

      String Email = txtEmailDangNhap.getText();
      String Pass = txtPassDangNhap.getText();
      UserDAO dao = new UserDAO();
      User u = dao.selectByEmail(Email);
      
      
         if (!txtQR.getText().isEmpty()) {
            String filePath = file.getAbsolutePath();
            String charset = "UTF-8";

            Map<EncodeHintType, ErrorCorrectionLevel> hashMap = new HashMap<>();
            hashMap.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.L);
            String qrCodeData = readQR(filePath, charset, hashMap);
          
            System.out.println(qrCodeData);
            
            String[] qrCodeParts = qrCodeData.split(" ");
            String emailQR = qrCodeParts[0];
	    String password = qrCodeParts[1];
            User u1 = dao.selectByEmail(emailQR);
            if (u1 != null && Encrypt.checkPassword(password, u1.getPassword())) {
                Check.user = u1;
            ((mainform)getParent()).updateStatus();
            ((mainform)getParent()).renderPRODUCT();
            ((mainform)getParent()).hoverBtnProfile();
            ((mainform)getParent()).renderDETAIL_ORDER();
            ((mainform)getParent()).renderWishLists(Integer.parseInt(u1.getId()));
            ((mainform)getParent()).renderAddress_User();
            ((mainform)getParent()).renderChiTietThanhToan();
                this.dispose();
            }else{
                ThongBao.alert(this, "Mã QR không hợp lệ!");
            }
        }else{  
        
             
        if(Email.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập Email!");
            return;
        }
        
        if(Pass.equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu!");
            return;
        }
      
        if(u == null){
            JOptionPane.showMessageDialog(this, "Emai hoặc mật khẩu không đúng!");
            return;
        }
        
        if(!Encrypt.checkPassword(Pass, u.getPassword())) {
            JOptionPane.showMessageDialog(this, "Emai hoặc mật khẩu không đúng!");
            return;
        }
        
        
            Check.user = u;
            ((mainform)getParent()).updateStatus();
            ((mainform)getParent()).renderPRODUCT();
            ((mainform)getParent()).hoverBtnProfile();
            ((mainform)getParent()).renderDETAIL_ORDER();
            ((mainform)getParent()).renderWishLists(Integer.parseInt(u.getId()));
            ((mainform)getParent()).renderAddress_User();
            ((mainform)getParent()).renderChiTietThanhToan();
            this.dispose();
       
         }
       
    }
    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        try {
            checkDangnhap();

        } catch (SQLException ex) {
            ex.getMessage();
        } catch (IOException ex) {
        Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
    } catch (NotFoundException ex) {
        Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangNhapMouseClicked

    }//GEN-LAST:event_btnDangNhapMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void btnQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQRActionPerformed
         JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Attachment");
//        chooser.setMultiSelectionEnabled(true);
    chooser.setCurrentDirectory(new File("D:\\FPT Polytechnic\\Ki4\\DuAn1\\admin\\java-ui-dashboard-001\\part 3\\ui-dashboard-001\\src\\com\\raven\\QRCode\\Users"));
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
         file = new File(""+chooser.getSelectedFile());
         txtQR.setText(file.getName());
        }
    }//GEN-LAST:event_btnQRActionPerformed

    private void lblQuenMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMatKhauMouseClicked
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);

        FormQuenMatKhau formQuenMatKhau = new FormQuenMatKhau(parentFrame, true);
        formQuenMatKhau.setLocationRelativeTo(null);
        this.dispose();
        formQuenMatKhau.setVisible(true);
        formQuenMatKhau.setAlwaysOnTop(true);
    }//GEN-LAST:event_lblQuenMatKhauMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        UIManager.put("TextComponent.arc", 30);
        UIManager.put("Button.arc", 30);

        FlatLightLaf.setup();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhap dialog = new DangNhap(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JdlDangNhap;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnQR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JTextField txtEmailDangNhap;
    private javax.swing.JPasswordField txtPassDangNhap;
    private javax.swing.JTextField txtQR;
    // End of variables declaration//GEN-END:variables

  
    
        public static String readQR(String path, String charset,
             Map<EncodeHintType, ErrorCorrectionLevel> hashMap)
            		 throws FileNotFoundException, IOException, NotFoundException {
		 BinaryBitmap binaryBitmap = new BinaryBitmap(new HybridBinarizer(
				 new BufferedImageLuminanceSource(
						 ImageIO.read(new FileInputStream(path)))));
		 Result result = new MultiFormatReader().decode(binaryBitmap);

		 return result.getText();
    }
    
}
