/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import Entity.Payment_Type;
import Entity.User;
import Entity.User_Payment_Method;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import dao.Payment_TypeDAO;
import dao.UserDAO;
import dao.User_Payment_MethodDAO;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Hashtable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import utils.Validate;
import javax.swing.JOptionPane;
import utils.Check;
import utils.Encrypt;
import utils.ThongBao;

/**
 *
 * @author ACER
 */
public class NewPaymentMethod extends javax.swing.JDialog {

    private Frame NewPaymentMethod;
    User_Payment_MethodDAO upmDao = new User_Payment_MethodDAO();
    Payment_TypeDAO ptDAO = new Payment_TypeDAO();
    /**
     * Creates new form DangKy
     */
    public NewPaymentMethod(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        init();
        setLocationRelativeTo(null);
    }
    
    public void init()
    {
        initPaymentType();
    }
    
    public void initPaymentType()
    {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboPaymentType.getModel();
        model.removeAllElements();
        
        List<Payment_Type> products = ptDAO.selectAll();
        for (Payment_Type pr : products) {
            model.addElement(pr);
//            System.out.println(pr);
        }
    
    }
    
    public boolean isVali()
    {
        if(txtCardHoderName.getText().equals(""))
        {
            ThongBao.alert(this, "Ô tên chủ thẻ đang trống");
            return false;
        }
        if(txtCardNumber.getText().equals(""))
        {
            ThongBao.alert(this, "Ô mã số thẻ đang trống");
            return false;
        }
        if(txtExpiryDate.getDate() == null)
        {
            ThongBao.alert(this, "Ô ngày hết hạn đang trống");
            return false;
        }
        if(txtProvider.getText().equals(""))
        {
            ThongBao.alert(this, "Ô nhà cung cấp đang trống");
            return false;
        }
        return true;
    }
    
    public void createPaymentMethod()
    {
        User u = Check.user;
        Payment_Type pt = (Payment_Type) cboPaymentType.getSelectedItem();
        if(u == null)
        {
            ThongBao.alert(this, "Hãy đăng nhập");
            return;
        }
        if(isVali())
        {
            try {
                User_Payment_Method entity = new User_Payment_Method();
                entity.setUser_id(Integer.parseInt(u.getId()));
                entity.setCard_holder_name(txtCardHoderName.getText());
                entity.setCard_number(txtCardNumber.getText());
                entity.setExpiry_date(txtExpiryDate.getDate());
                entity.setPayment_type_id(pt.getId());
                entity.setProvider(txtProvider.getText());
                entity.setIs_default(true);
                upmDao.insert(entity);
                ThongBao.alert(this, "Thêm thành công");
                this.dispose();
            } catch (Exception e) {
                e.printStackTrace();
                ThongBao.alert(this, "Loi: "+e.getMessage());
            }
            ;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDangKyPayMent = new javax.swing.JButton();
        txtProvider = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        txtCardNumber = new javax.swing.JTextField();
        txtCardHoderName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cboPaymentType = new javax.swing.JComboBox<>();
        txtExpiryDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 3, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Payment Method");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 400, -1));

        btnDangKyPayMent.setBackground(new java.awt.Color(25, 135, 84));
        btnDangKyPayMent.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangKyPayMent.setForeground(new java.awt.Color(255, 255, 255));
        btnDangKyPayMent.setText("ĐĂNG KÍ");
        btnDangKyPayMent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyPayMentActionPerformed(evt);
            }
        });
        jPanel2.add(btnDangKyPayMent, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 590, 176, 50));
        jPanel2.add(txtProvider, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 410, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Mã số thẻ");
        jLabel5.setAutoscrolls(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 140, 30));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setText("Tên chủ thẻ");
        jLabel10.setAutoscrolls(true);
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 90, 30));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setText("Nhà cung cấp");
        jLabel11.setAutoscrolls(true);
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 110, 30));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setText("Ngày hết hạn");
        jLabel12.setAutoscrolls(true);
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 120, 30));

        btnHuy.setBackground(new java.awt.Color(25, 135, 84));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("HỦY");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel2.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 176, 50));
        jPanel2.add(txtCardNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 410, 40));
        jPanel2.add(txtCardHoderName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 410, 40));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setText("Kiểu thanh toán");
        jLabel8.setAutoscrolls(true);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 140, 30));

        jPanel2.add(cboPaymentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 410, 40));
        jPanel2.add(txtExpiryDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 410, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 66, 640, 674));

        jLabel6.setText("Trang Chủ/");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 21, -1, -1));

        jLabel7.setForeground(new java.awt.Color(25, 135, 82));
        jLabel7.setText("Đăng Ký");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 21, 54, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    
    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnDangKyPayMentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyPayMentActionPerformed
        createPaymentMethod();
    }//GEN-LAST:event_btnDangKyPayMentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPaymentMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPaymentMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPaymentMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPaymentMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewPaymentMethod dialog = new NewPaymentMethod(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKyPayMent;
    private javax.swing.JButton btnHuy;
    private javax.swing.JComboBox<String> cboPaymentType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCardHoderName;
    private javax.swing.JTextField txtCardNumber;
    private com.toedter.calendar.JDateChooser txtExpiryDate;
    private javax.swing.JTextField txtProvider;
    // End of variables declaration//GEN-END:variables
}
